name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  macos:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test --enable-code-coverage --sanitize=thread
      - name: Generate documentation
        uses: sukhrobkhakimov/publish-jazzy-docs@v1
        with:
          personal_access_token: ${{ secrets.ACCESS_TOKEN }}
          args: "--module Chaqmoq --theme fullwidth --root-url https://chaqmoq.dev/chaqmoq --source-host github --source-host-url https://github.com/chaqmoq/chaqmoq"
  ubuntu:
    runs-on: ubuntu-latest
    container: swift:5.10-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test --enable-code-coverage --enable-test-discovery --sanitize=thread
      - name: Generate coverage report
        run: llvm-cov export -format="lcov" .build/debug/chaqmoqPackageTests.xctest -instr-profile=.build/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests" > coverage.lcov
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
