name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  macos:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test --enable-code-coverage --sanitize=thread
  ubuntu:
    runs-on: ubuntu-latest
    container: swift:5.10-jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test --enable-code-coverage --enable-test-discovery --sanitize=thread
